### ISSUE TITLE
Set up testing

### ISSUE THREAD

**Issue by hallvors** [Asynchq/boar#36]
We need some framework for running tests. Here are some requirements or thoughts about the architecture:

1. Tests are written in Python, using the requests module to communicate with Boar itself and simple unittest assertations
2. We need a test runner which invokes Boar in either Gecko or Phantom mode, and start the test script when the SlimerJS/PhantomJS instance is ready

If we use the "nose" module, the framework might  consist of a single Python file doing this:

1. Set up a local server listening for the callback saying Boar is ready
2. Run a Boar instance (execute ```bin/boar gecko``` - or ```webkit```)
3. When the Boar instance pings the server in step 1, do 

    import nose
    nose.main()

to run tests.

4. Repeat from step 2 above for ```webkit```

Might work..

**Comment by ronoc** [comment]
Good thinking Hallvord, but ideally it would be good to write our tests with the Node libs we have built already. For specifying the various engines you can test the boar client using jannah-client. 

https://github.com/Asynchq/jannah-client.

That way we can keep the entire project in Node, using callbacks properly and already taking advantage of all the testing Node stuff that we are using already. 

Can you attach your python scripts here so that we can take a look. It should be relatively straight forward to port them to the existing test suite on jannah-client.

**Comment by hallvors** [comment]
I barely got started on the Python "framework" part, but here's one test for the window.orientation usage plugin:
https://gist.github.com/hallvors/9061f046236c275060e1

Here's one for the API - for the geterrorlog command:
https://gist.github.com/hallvors/1d33c81367ebc33e38f0
and another one for the getconsolelog command:
https://gist.github.com/hallvors/348197691d48bd5982c8

**Comment by hallvors** [comment]
For those tests, the expected results are the same across engines, but we also need tests where that isn't the case.
