### ISSUE TITLE
Plugin for CSS analysis

### ISSUE THREAD

**Issue by ronoc** [Asynchq/boar#42]
Polish the CSS analysis code and turn it into a plugin - it's somewhat sub-optimal, would be nicer if we could access the CSS object model cross-domain through the DOM..

**Comment by seiflotfy** [comment]
The plugin for CSS would not work, since we'd have to actually write css parsers and evaluators by hand. 
NodeJS provides us with way better options to work on CSS.
I prefer having it done on the outside and we just provide the CSS

**Comment by ronoc** [comment]
https://gist.github.com/hallvors/064d240600f68527123c

**Comment by ronoc** [comment]
https://gist.github.com/hallvors/064d240600f68527123c

**Comment by seiflotfy** [comment]
Where can I find css-analysis.js ?

**Comment by ronoc** [comment]
Sorry I pasted the same thing twice. 
@seiflotfy here it is https://gist.github.com/hallvors/b0be544c17c1dac413d4

**Comment by hallvors** [comment]
Thanks @ronoc :)
I'd like to start getting data from this script now, even if it's going to be a bit slow to run.
If and when we move to WebExtension-addons for controlling the browser, we can probably use the debugger APIs to get access to the CSS object model without origin limitations. (The developer tools can of course access anything..). But that's some time away..

**Comment by ronoc** [comment]
@hallvors That script is breaking in interesting ways

Script Error: TypeError: \'[object Object],[object Object],[object Object]\' is not a function (near \'...])(); })()...\')\n       Stack:\n         -> phantomjs://webpage.evaluate(): 76\n         -> phantomjs://webpage.evaluate(): 80\n'
Script Error: Error: [].apply is not a function\n       Stack:\n         -> phantomjs://webpage.evaluate(): 1\n         -> phantomjs://webpage.evaluate(): 1\n'

Right now its preventing that PR above from landing.

**Comment by hallvors** [comment]
I haven't seen that exact error I think, but I tested a bit in Phantom - is this better?
http://hallvord.com/temp/moz/css-analysis.js 

Note: this script does not attempt to detect if a -webkit- rule *has* standard equivalents. Adding that is the next step - but please try to get this version running already :)

**Comment by hallvors** [comment]
I'll do more work on this, so I'm reopening.

**Comment by hallvors** [comment]
Two quick hacks to save resources and make it simpler to integrate this:

1) Only actually run the plugin if we're testing an engine with support for the relevant CSS stuff (```webkitTransition in document.documentElement.style``` or similar?)
2) Don't go through all elements - limit ourselves to for example ```querySelectorAll('div, nav, li, a, span')``` - or similar. Span might also go.

**Comment by hallvors** [comment]
I've done some [more work on optimising this](https://github.com/Asynchq/boar/tree/hallvors/cssanalysis) - but since I run Compatipede on a somewhat slow laptop I don't know it's now fast enough for production or not. If this still isn't going to be fast enough, I think Seif is right that we need to find a solution outside of the browser. I have used the Rework parser for [CSS-fixme](https://webcompat.com/tools/cssfixme) and it's definitely an option - we can re-use parts of CSS-fixme as well.

I need to fix up that branch so the Travis tests pass - afterwards it would be useful to try it out on production hardware..

**Comment by hallvors** [comment]
(I'll also note that I came across the --web-security=no command line parameter for phantomjs which would solve this problem since one could just access the CSSOM directly for all stylesheets. However, it's not a good solution because we're definitely interested in seeing for example different cross-domain access errors reported.. Being able to disable cross-origin security only for CSSStyleSheet.cssRules would be great..)

**Comment by hallvors** [comment]
Tests pass here with the latest fix: https://github.com/Asynchq/boar/tree/hallvors/cssanalysis
