### ISSUE TITLE
CSS analysis plugin is blocking event loop

### ISSUE THREAD

**Issue by dainis** [Asynchq/boar#52]
CSS analysis takes quite a bit of time and it is completely blocking(for some pages takes even 30+ seconds to execute, eg., [url](http://www.glamour.com/entertainment/2015/08/stephen-colbert-shares-why-he-thinks-women-should-be-in-charge-of-everything) from [webcompat/1540](https://github.com/webcompat/web-bugs/issues/1540)) and as a result ping times out

maybe those loops could be wrapped with setTimeouts so that it would free up event loop

then there would be an issue with getting plugin results, somehow it should signal that plugin results haven't been computed yet and client has to retry again

**Comment by ronoc** [comment]
:+1: 
Its quite a bit of work at this stage to move over to this design. @hallvors let us know what you think. It will require a rewrite of the plugins architecture, all plugins will need to be moved to an async pattern. 
The client will need to then be mindful of the fact that some plugins might be completed and keep retrying in order to leave enough time for long running plugins to complete. A non-blocking architecture would be better, but it is a big change.

**Comment by hallvors** [comment]
I think we can just close this issue - one day we might have non-blocking plugin threads (or more accurately a separate worker thread capable of responding to pings even while plugin code runs on the main thread) with a WebExtensions-based control mechanism for the browser engine(s). Until then it doesn't make much sense to work on this.
